# Use root/example as user/password credentials
version: '3.7'

services:

  db:
    image: mariadb
    restart: always
    ports:
       - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks: 
      - internal-container-network
    volumes:
      - mariadb-data:/var/lib/mysql
      
  
  kaftrio:
     image: kaf-image:v2
     restart: always
     volumes:
      - mariadb-data:/root/.aspnet/DataProtection-Keys
     ports:
       - 8050:80
     depends_on: 
       - db
     entrypoint: ["dotnet", "api.dll"]
     networks: 
       - internal-container-network 
   
networks:
  internal-container-network:
    driver: bridge
volumes:
  mariadb-data:
  
